Support Sign Unsigned Tx
alephium/desktop-wallet pull request #791
Opened 2023-08-25 14:38 UTC by h0ngcha0

2023-08-25 14:39 UTC, h0ngcha0 commented on src/modals/SignUnsignedTx/index.tsx
> +              {t('Sign')}
To h0ngcha0: fix translation

2023-08-28 05:57 UTC, nop33 commented on locales/en-US/translation.json
> +  "Sign": "Sign",
After adding the English entry (as you just did) you can run:

```
npm run syncTranslationFiles
```

and commit the diff.

2023-08-28 07:14 UTC, h0ngcha0 commented on locales/en-US/translation.json
> +  "Sign": "Sign",
I see, thanks! I see that this command populates all the language specific files with the English text. Do we need to wait until all are translated before we can merge?

2023-08-28 07:25 UTC, mvaivre commented on locales/en-US/translation.json
> +  "Sign": "Sign",
No, only the English version needs to be up to date. The other translations can come later (we rely on the community for those!).

2023-08-28 07:57 UTC, h0ngcha0 commented on locales/en-US/translation.json
> +  "Sign": "Sign",
Thanks! :+1:

2023-08-28 09:47 UTC, mvaivre commented on src/modals/SignUnsignedTx/index.tsx
> +      {decodedUnsignedTx ? (
Nit: We could use the following shorter syntax:

```ts
decodedUnsignedTx && ...
```

2023-08-28 09:47 UTC, mvaivre commented on src/modals/SignUnsignedTx/index.tsx
> +  useEffect(() => {
Nit: As the `decodeUnsignedTx` function is used only once here, and for consistency sake (avoid the `.then()` syntax), we could declare and call the function right inside the `useEffect`:

```ts
useEffect(() => {
  const decodeUnsignedTx = async () => {
    setIsLoading(true)
    ...
    setDecodedUnsignedTx({
       txId: decodedResult.unsignedTx.txId,
       fromGroup: decodedResult.fromGroup,
       toGroup: decodedResult.toGroup,
       unsignedTx: txData.unsignedTx,
       gasAmount: decodedResult.unsignedTx.gasAmount,
       gasPrice: BigInt(decodedResult.unsignedTx.gasPrice)
     })
    setIsLoading(false)
 }

  decodeUnsignedTx()
, [...]}
```

2023-08-28 09:47 UTC, mvaivre commented on src/modals/SignUnsignedTx/index.tsx
> +          <FooterButton onClick={() => handleSign()} disabled={isLoading || !decodedUnsignedTx}>
```ts
onClick={handleSign}
```

2023-08-28 10:46 UTC, mvaivre commented
Again, great work! I've done some functional testing and it seems to work. However, I find confusing that the way the unsigned transaction is encoded seems to differ from what I see in the multi-sig tool:

<img width="638" alt="image" src="https://github.com/alephium/desktop-wallet/assets/6715943/f9757d04-13dc-464b-b89c-5a8ccf60e6b6">

vs 

![image](https://github.com/alephium/desktop-wallet/assets/6715943/88107c22-9934-491c-af90-efd88163f54c)


As a user I was expecting to be able to compare the 2 strings.

2023-08-28 11:03 UTC, polarker commented
@mvaivre  That's a great question. They were the same initially, but then Thomas and Polto were confused too because they used that raw tx string with Swagger.

Now I think it's good to keep them same again. Nice one!

2023-08-28 11:24 UTC, h0ngcha0 commented
> 

I guess we will update the app, right?

2023-08-28 11:25 UTC, h0ngcha0 commented
> @mvaivre That's a great question. They were the same initially, but then Thomas and Polto were confused too because they used that raw tx string with Swagger.
> 
> Now I think it's good to keep them same again. Nice one!


I guess we will update the app, right?

2023-08-28 11:26 UTC, h0ngcha0 commented
> > @mvaivre That's a great question. They were the same initially, but then Thomas and Polto were confused too because they used that raw tx string with Swagger.
> > Now I think it's good to keep them same again. Nice one!
> 
> I guess we will update the app, right?

Sorry, just saw the update on app.

2023-08-28 14:05 UTC, polarker requested changes
LGTM

2023-08-28 14:05 UTC, polarker approved these changes
LGTM

2023-08-28 16:50 UTC, mvaivre approved these changes

2023-08-28 21:38 UTC, merged